### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by acheong08** [mitchbregs/vectorizer-ai#1]
I just saw this and kinda laughed because I wrote the exact same thing but by scraping (the official API wasn't available) and I see that the initial commit here came just a week after which meant I could've literally just waited a bit for this to come out.

Good work.

**Comment by mitchbregs** [comment]
> I just saw this and kinda laughed because I wrote the exact same thing but by scraping (the official API wasn't available) and I see that the initial commit here came just a week after which meant I could've literally just waited a bit for this to come out.
> 
> 
> 
> Good work.

Haha, @acheong08 - glad you stumbled upon this! Enjoy. And thank you!
